name: Starter Github Action
run-name: ${{ github.actor}} is testing out GITHUB ACtions 
on: 
    pull_request:
    pull_request_target:
jobs: 
    Explore-Github-Actions:
        runs-on: ubuntu-latest
        steps: 
            - run: echo "The job was automatically triggered by a ${{ github.event_name}} event."
            - run: echo "This job is now running on a ${{ runner.arch}} server"
            - run: echo "Testing a light bit of ls, current parameter ${{ github.event.pull_request.body}}"
            - run: echo "Command run ${{ github.event_name}}"